--!strict

return {
	DISABLED = {
		THUMB_COLOR = Color3.fromRGB(47, 47, 47),
		CIRCLE_COLOR = Color3.fromRGB(126, 126, 126),
		CIRCLE_POSITION = UDim2.fromScale(0, 0.5),
		CIRCLE_ANCHOR_POINT = Vector2.new(0, 0.5),
	},
	ENABLED = {
		THUMB_COLOR = Color3.fromRGB(255, 255, 255),
		CIRCLE_COLOR = Color3.fromRGB(34, 34, 34),
		CIRCLE_POSITION = UDim2.fromScale(1, 0.5),
		CIRCLE_ANCHOR_POINT = Vector2.new(1, 0.5),
	},
}
